# Generated by Django 5.0.6 on 2026-05-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.FloatField(default=0.5)),
                ('influence_score', models.FloatField(default=0.5)),
                ('relationship_type', models.CharField(default='neutral', max_length=50)),
                ('interaction_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='agents.agent')),
                ('agent_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='agents.agent')),
            ],
            options={
                'db_table': 'social_relationships',
                'indexes': [models.Index(fields=['agent_a'], name='social_rela_agent_a_83883d_idx'), models.Index(fields=['agent_b'], name='social_rela_agent_b_6fea52_idx')],
                'unique_together': {('agent_a', 'agent_b')},
            },
        ),
    ]
