# Generated by Django 5.0.6 on 2026-05-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fear', models.FloatField(default=0.0)),
                ('greed', models.FloatField(default=0.0)),
                ('trust', models.FloatField(default=0.5)),
                ('optimism', models.FloatField(default=0.5)),
                ('stress', models.FloatField(default=0.0)),
                ('panic', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(default='neutral', max_length=20)),
                ('tick_number', models.BigIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_logs', to='agents.agent')),
            ],
            options={
                'db_table': 'agent_emotion_logs',
            },
        ),
    ]
