# Generated by Django 5.0.6 on 2026-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='idle', max_length=20)),
                ('speed_multiplier', models.IntegerField(default=1)),
                ('current_tick', models.BigIntegerField(default=0)),
                ('current_day', models.IntegerField(default=1)),
                ('current_month', models.IntegerField(default=1)),
                ('current_year', models.IntegerField(default=1)),
                ('current_hour', models.IntegerField(default=0)),
                ('total_agents', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'simulation_config',
            },
        ),
    ]
