# Generated by Django 5.0.6 on 2026-05-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationconfig',
            name='celery_task_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='simulationconfig',
            name='current_week',
            field=models.IntegerField(default=1),
        ),
    ]
