# Generated by Django 5.0.6 on 2026-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(choices=[('consumer', 'Consumer'), ('worker', 'Worker'), ('trader', 'Trader'), ('investor', 'Investor'), ('business_owner', 'Business Owner'), ('manufacturer', 'Manufacturer'), ('government', 'Government Agent'), ('banker', 'Banker'), ('influencer', 'Influencer'), ('researcher', 'Researcher'), ('resource_supplier', 'Resource Supplier')], max_length=50)),
                ('intelligence_tier', models.IntegerField(default=3)),
                ('wealth', models.FloatField(default=1000.0)),
                ('income', models.FloatField(default=0.0)),
                ('debt', models.FloatField(default=0.0)),
                ('emotion_fear', models.FloatField(default=0.0)),
                ('emotion_greed', models.FloatField(default=0.0)),
                ('emotion_trust', models.FloatField(default=0.5)),
                ('emotion_optimism', models.FloatField(default=0.5)),
                ('emotion_stress', models.FloatField(default=0.0)),
                ('emotion_panic', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(choices=[('neutral', 'Neutral'), ('fearful', 'Fearful'), ('greedy', 'Greedy'), ('trusting', 'Trusting'), ('optimistic', 'Optimistic'), ('stressed', 'Stressed'), ('panic', 'Panic')], default='neutral', max_length=20)),
                ('risk_score', models.FloatField(default=0.5)),
                ('strategy', models.CharField(choices=[('conservative', 'Conservative'), ('aggressive', 'Aggressive'), ('balanced', 'Balanced'), ('speculative', 'Speculative'), ('cooperative', 'Cooperative')], default='balanced', max_length=50)),
                ('social_influence', models.FloatField(default=0.5)),
                ('cooperation_rate', models.FloatField(default=0.5)),
                ('is_employed', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_action', models.CharField(default='idle', max_length=100)),
                ('last_action_tick', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
    ]
