# Generated by Django 5.0.6 on 2026-05-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='agent',
            name='agent_prof_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agent_emotion_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agent_tier_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='agent',
            name='agent_wealth_idx',
        ),
    ]
