# Generated by Django 5.0.6 on 2026-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('recession', 'Recession'), ('market_crash', 'Market Crash'), ('panic_wave', 'Panic Wave'), ('monopoly', 'Monopoly Formation'), ('innovation_boom', 'Innovation Boom'), ('unemployment_crisis', 'Unemployment Crisis'), ('shortage', 'Resource Shortage'), ('recovery', 'Economic Recovery')], max_length=50)),
                ('severity', models.FloatField(default=1.0)),
                ('description', models.TextField()),
                ('simulation_day', models.IntegerField()),
                ('simulation_month', models.IntegerField()),
                ('simulation_year', models.IntegerField()),
                ('tick_number', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'simulation_events',
                'ordering': ['-tick_number'],
            },
        ),
    ]
