# Generated by Django 5.0.6 on 2026-05-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='simulationevent',
            index=models.Index(fields=['event_type'], name='simulation__event_t_baad37_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationevent',
            index=models.Index(fields=['tick_number'], name='simulation__tick_nu_d4244e_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationevent',
            index=models.Index(fields=['simulation_year', 'simulation_month', 'simulation_day'], name='simulation__simulat_ebd4ba_idx'),
        ),
    ]
