# Generated by Django 5.0.6 on 2026-05-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision_input', models.JSONField()),
                ('decision_output', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('tick_number', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neural_logs', to='agents.agent')),
            ],
            options={
                'db_table': 'neural_logs',
            },
        ),
    ]
