# Generated by Django 5.0.6 on 2026-05-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='neurallog',
            index=models.Index(fields=['agent', 'tick_number'], name='neural_logs_agent_i_e2f0d0_idx'),
        ),
    ]
