# Generated by Django 5.0.6 on 2026-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.FloatField(default=20.0)),
                ('interest_rate', models.FloatField(default=5.0)),
                ('government_spending', models.FloatField(default=10000.0)),
                ('subsidy_level', models.FloatField(default=0.0)),
                ('stimulus_active', models.BooleanField(default=False)),
                ('stimulus_amount', models.FloatField(default=0.0)),
                ('market_regulation', models.FloatField(default=50.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_state',
            },
        ),
    ]
