# Generated by Django 5.0.6 on 2026-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('tick_number', models.BigIntegerField()),
                ('simulation_day', models.IntegerField()),
                ('simulation_month', models.IntegerField()),
                ('simulation_year', models.IntegerField()),
                ('state_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'simulation_snapshots',
                'ordering': ['-tick_number'],
            },
        ),
    ]
