# Generated by Django 5.0.6 on 2026-05-17 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdp', models.FloatField(default=100000.0)),
                ('inflation', models.FloatField(default=2.0)),
                ('unemployment', models.FloatField(default=5.0)),
                ('market_confidence', models.FloatField(default=70.0)),
                ('wealth_gini', models.FloatField(default=0.35)),
                ('resource_index', models.FloatField(default=100.0)),
                ('economic_stability', models.FloatField(default=75.0)),
                ('simulation_day', models.IntegerField(default=1)),
                ('simulation_month', models.IntegerField(default=1)),
                ('simulation_year', models.IntegerField(default=1)),
                ('simulation_hour', models.IntegerField(default=0)),
                ('tick_number', models.BigIntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'economy_state',
                'ordering': ['-tick_number'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('resource', models.CharField(max_length=100)),
                ('simulation_day', models.IntegerField()),
                ('simulation_month', models.IntegerField()),
                ('simulation_year', models.IntegerField()),
                ('tick_number', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='agents.agent')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='agents.agent')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
