# Generated by Django 5.0.6 on 2026-05-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='economystate',
            name='gdp_growth_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='economystate',
            name='total_money_supply',
            field=models.FloatField(default=500000.0),
        ),
        migrations.AddField(
            model_name='economystate',
            name='total_wealth',
            field=models.FloatField(default=500000.0),
        ),
        migrations.AddIndex(
            model_name='economystate',
            index=models.Index(fields=['tick_number'], name='economy_sta_tick_nu_ba1945_idx'),
        ),
        migrations.AddIndex(
            model_name='economystate',
            index=models.Index(fields=['simulation_year', 'simulation_month', 'simulation_day'], name='economy_sta_simulat_5f6514_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tick_number'], name='transaction_tick_nu_0b45dd_idx'),
        ),
    ]
