# Generated by Django 5.0.6 on 2026-05-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_supply', models.FloatField(default=100.0)),
                ('oil_supply', models.FloatField(default=100.0)),
                ('energy_availability', models.FloatField(default=100.0)),
                ('housing_supply', models.FloatField(default=100.0)),
                ('water_resources', models.FloatField(default=100.0)),
                ('food_price', models.FloatField(default=10.0)),
                ('oil_price', models.FloatField(default=50.0)),
                ('energy_price', models.FloatField(default=30.0)),
                ('housing_price', models.FloatField(default=200.0)),
                ('water_price', models.FloatField(default=5.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resource_state',
            },
        ),
    ]
