# Generated by Django 5.0.6 on 2026-05-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestate',
            name='energy_availability',
            field=models.FloatField(default=82.0),
        ),
        migrations.AlterField(
            model_name='resourcestate',
            name='food_supply',
            field=models.FloatField(default=85.0),
        ),
        migrations.AlterField(
            model_name='resourcestate',
            name='housing_supply',
            field=models.FloatField(default=75.0),
        ),
        migrations.AlterField(
            model_name='resourcestate',
            name='oil_supply',
            field=models.FloatField(default=80.0),
        ),
        migrations.AlterField(
            model_name='resourcestate',
            name='water_resources',
            field=models.FloatField(default=90.0),
        ),
    ]
