# Generated by Django 5.0.6 on 2026-05-17 05:29

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('importance', models.FloatField(default=0.5)),
                ('memory_type', models.CharField(default='experience', max_length=50)),
                ('tick_number', models.BigIntegerField(default=0)),
                ('simulation_day', models.IntegerField(default=1)),
                ('simulation_year', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='agents.agent')),
            ],
            options={
                'db_table': 'agent_memories',
                'ordering': ['-importance', '-tick_number'],
                'indexes': [models.Index(fields=['agent', 'importance'], name='agent_memor_agent_i_ef5663_idx'), models.Index(fields=['agent', 'tick_number'], name='agent_memor_agent_i_6a5f0d_idx')],
            },
        ),
    ]
